imprimiendo libros
Swarzstein/awesome-books pull request #1
Opened 2022-10-11 20:01 UTC by Swarzstein

2022-10-12 18:23 UTC, julie-ify requested changes
## Hi @Swarzstein,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] You are required to display date and time using the luxon package under the right side of the menu bar. Kindly do that

  
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 18:23 UTC, julie-ify commented on modules/books.js
> +    // console.log('this is the books array:\n' + localStorage.getItem('BOOkS'));
- [ ] Kindly remove these commented console logs as they look untidy and can make your code had to read.

2022-10-12 18:23 UTC, julie-ify commented on index.js
> +});
- [ ] Remove these console logs

2022-10-12 18:23 UTC, julie-ify commented on modules/printer.js
> +      // console.log(`the book with id = ${bookId} will be deleted`);
- [ ] Remove the console log

2022-10-12 18:23 UTC, julie-ify commented on index.js
> +import Book from './modules/books.js';// eslint-disable-next-line
- [ ] Kindly enable linters here and fix the resulting errors. Linters help us write standardized code and meet recommended best practices

2022-10-12 18:23 UTC, julie-ify commented on modules/books.js
> +    books = JSON.parse(localStorage.getItem('BOOkS'));// eslint-disable-next-line
- [ ] Kindly enable linter

2022-10-12 18:23 UTC, julie-ify commented on modules/printer.js
> +// eslint-disable-next-line
- [ ] Kindly enable linter here

2022-10-12 23:16 UTC, Whoistolu reviewed
Hi @Swarzstein 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that whose linters fail. Currently, the Elslint that is supposed to standardize your JS code is failing. Kindly fix this before requesting for another review as it is a core project requirement.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-13 00:31 UTC, omarsalem7 approved these changes
Hi @Swarzstein  😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-19 20:55 UTC, merged